Upgrade project to .Net 8 LTS
error CS0246: The type or namespace name 'EventProvider' could not be found (are you missing a using directive or an assembly reference?)