Fix error C2440: 'initializing': cannot convert from 'const wchar_t []' to 'LPWSTR' errors
Error listing:
1>C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(41,17): error C2440: 'initializing': cannot convert from 'const wchar_t [24]' to 'LPWSTR'
1>    C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(41,17):
1>    Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(47,10): error C2440: 'initializing': cannot convert from 'const wchar_t [5]' to 'LPWSTR'
1>    C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(47,10):
1>    Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(48,10): error C2440: 'initializing': cannot convert from 'const wchar_t [4]' to 'LPWSTR'
1>    C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(48,10):
1>    Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(49,10): error C2440: 'initializing': cannot convert from 'const wchar_t [8]' to 'LPWSTR'
1>    C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(49,10):
1>    Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(50,10): error C2440: 'initializing': cannot convert from 'const wchar_t [7]' to 'LPWSTR'
1>    C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(50,10):
1>    Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>C:\Dev\WindowsEventQuery\ManifestBasedEventLog\Main.cpp(51,10): error C2440: 'initializing': cannot convert from 'const wchar_t [1]' to 'LPWSTR'